'use client';
import { jsPDF } from 'jspdf';
import { FileDown } from 'lucide-react';
import toast from 'react-hot-toast';

interface ReportData {
  userName: string;
  studentId: string;
  targetExam: string;
  totalAttempted: number;
  totalCorrect: number;
  accuracy: number;
  streakDays: number;
  subjectMastery: Record<string, number>;
  weakTopics: { topic: string; subject: string; accuracy: number }[];
  trend: { date: string; total: number; correct: number; accuracy: number }[];
}

export function generatePDFReport(data: ReportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('VIDYA', 20, 25);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('AI-Powered Learning Report', 20, 33);
  
  // Date
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN', { 
    day: 'numeric', month: 'long', year: 'numeric' 
  })}`, pageWidth - 60, 25);

  y = 55;
  doc.setTextColor(0, 0, 0);

  // Student Info
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Student Information', 20, y);
  y += 10;
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${data.userName}`, 20, y);
  doc.text(`Student ID: ${data.studentId}`, 100, y);
  y += 7;
  doc.text(`Target Exam: ${data.targetExam}`, 20, y);
  doc.text(`Study Streak: ${data.streakDays} days`, 100, y);
  
  y += 15;

  // Overall Stats
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Performance Overview', 20, y);
  y += 10;

  // Stats boxes
  const stats = [
    { label: 'Questions', value: data.totalAttempted.toString() },
    { label: 'Correct', value: data.totalCorrect.toString() },
    { label: 'Accuracy', value: `${data.accuracy}%` },
  ];
  
  const boxWidth = 50;
  stats.forEach((stat, i) => {
    const x = 20 + i * (boxWidth + 10);
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(x, y, boxWidth, 25, 3, 3, 'F');
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(99, 102, 241);
    doc.text(stat.value, x + boxWidth / 2, y + 12, { align: 'center' });
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    doc.text(stat.label, x + boxWidth / 2, y + 20, { align: 'center' });
  });
  
  y += 35;
  doc.setTextColor(0, 0, 0);

  // Subject Mastery
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Subject Mastery', 20, y);
  y += 10;

  Object.entries(data.subjectMastery).forEach(([subject, score]) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`${subject.charAt(0).toUpperCase() + subject.slice(1)}`, 20, y);
    doc.text(`${Math.round(score)}%`, 170, y);
    
    // Progress bar
    doc.setFillColor(226, 232, 240);
    doc.roundedRect(60, y - 4, 100, 6, 2, 2, 'F');
    if (score > 0) {
      doc.setFillColor(99, 102, 241);
      doc.roundedRect(60, y - 4, Math.min(score, 100), 6, 2, 2, 'F');
    }
    y += 10;
  });

  y += 10;

  // Weak Topics
  if (data.weakTopics.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Areas Needing Improvement', 20, y);
    y += 10;

    data.weakTopics.slice(0, 5).forEach((topic, i) => {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`${i + 1}. ${topic.topic} (${topic.subject})`, 25, y);
      doc.setTextColor(239, 68, 68);
      doc.text(`${topic.accuracy}%`, 170, y);
      doc.setTextColor(0, 0, 0);
      y += 8;
    });
  }

  y += 10;

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('This report was generated by VIDYA AI Tutor. Keep practicing!', pageWidth / 2, 280, { align: 'center' });

  // Save
  doc.save(`VIDYA_Report_${data.studentId}_${new Date().toISOString().split('T')[0]}.pdf`);
  toast.success('Report downloaded!');
}

export default function DownloadReportButton({ data }: { data: ReportData }) {
  return (
    <button onClick={() => generatePDFReport(data)}
      className="btn-secondary flex items-center gap-2">
      <FileDown className="w-4 h-4" /> Download Report
    </button>
  );
}
